sort: sorting.o lab_15_unit_test.o
	g++ -Wall -g -o  sort sorting.o lab_15_unit_test.o

Unit_test: lab_15_unit_test.cpp
	g++ -Wall -g -c lab_15_unit_test.cpp

sorting: sorting.cpp
	g++ -Wall -g -c sorting.cpp

clean:
	rm *.o sort