lab11test: lab11.o lab_11_unit_test.o 
	g++ -Wall -g -o lab11 lab11.o lab_11_unit_test.o 

lab11unitttest: lab_11_unit_test.cpp
	g++ -Wall -g -c lab_11_unit_test.cpp
	
lab11: lab11.cpp
	g++ -Wall -g -c lab11.cpp