lab1test: lab1.o lab_1_unit_test.o 
	g++ -Wall -g -o lab1 lab1.o lab_1_unit_test.o 

lab1unitttest: lab_1_unit_test.cpp
	g++ -Wall -g -c lab_1_unit_test.cpp
	
lab1: lab1.cpp
	g++ -Wall -g -c lab1.cpp
