lab2test: lab2.o lab_2_unit_test.o 
	g++ -Wall -g -o lab2 lab2.o lab_2_unit_test.o 

lab2Utest: lab_2_unit_test.cpp
	g++ -Wall -g -c lab_2_unit_test.cpp

lab2: lab2.cpp
	g++ -Wall -g -c lab2.cpp
	
clean:
	rm *.o lab2
	