lab10test: lab10.o lab_10_unit_test.o 
	g++ -Wall -g -o lab10 lab10.o lab_10_unit_test.o 

lab10unitttest: lab_10_unit_test.cpp
	g++ -Wall -g -c lab_10_unit_test.cpp
	
lab10: lab10.cpp
	g++ -Wall -g -c lab10.cpp