lab4test: DLList.o DLNode.o  
	g++ -Wall -g -o DLNode DLNode.o DLList.o  

Musical_Chairs.cpp: Musical_Chairs.cpp
	g++ -Wall -g -c Musical_Chairs.cpp

DLList.o: DLList.cpp
	g++ -Wall -g -c DLList.cpp

DLNode.o: DLNode.cpp
	g++ -Wall -g -c DLNode.cpp
	
clean:
	rm *.o DLNode