lab1test: sl_node.o sl_unit_test.o 
	g++ -Wall -g -o slnode sl_node.o sl_unit_test.o 

lab1unitttest: sl_unit_test.cpp
	g++ -Wall -g -c sl_unit_test.cpp
	
SLNode: sl_node.cpp
	g++ -Wall -g -c sl_node.cpp

clean:
	rm *.o slnode