lab3test: BST_node.o lab_3_unit_test.o 
	g++ -Wall -g -o BST_node BST_node.o lab_3_unit_test.o 

lab3Utest: lab_3_unit_test.cpp
	g++ -Wall -g -c lab_3_unit_test.cpp

BSTNode: BST_node.cpp
	g++ -Wall -g -c BST_node.cpp
	
clean:
	rm *.o lab3
	