lab8test: lab_8.o lab_8_unit_test.o 
	g++ -Wall -g -o lab8 lab_8.o lab_8_unit_test.o 

lab8unitttest: lab_8_unit_test.cpp
	g++ -Wall -g -c lab_8_unit_test.cpp
	
lab7: lab_7.cpp
	g++ -Wall -g -c lab_8.cpp