lab10test: MyATM.o BankAccounts.o Checking.o Credit_Card.o Savings.o
	g++ -Wall -g -o MyATM MyATM.o BankAccounts.o Checking.o Credit_Card.o Savings.o

BankAccounts: BankAccounts.cpp
	g++ -Wall -g -c BankAccounts.cpp
	
Checking: Checking.cpp
	g++ -Wall -g -c Checking.cpp
	
Assign2: MyATM.cpp
	g++ -Wall -g -c MyATM.cpp
	
Credit_Card: Credit_Card.cpp
	g++ -Wall -g -c Credit_Card.cpp
	
Savings: Savings.cpp
	g++ -Wall -g -c Savings.cpp
	
 # Links       : https://github.com/RussPowell/Hello-World.git
 #               https://hello-world-russpowell.c9users.io
 # Discovered that the # symbol is a comment line for this type of file