lab12test: item.o food_item.o magic_item.o lab_12_unit_test.o 
	g++ -Wall -g -o lab12 item.o food_item.o magic_item.o lab_12_unit_test.o 

lab12unitttest: lab_12_unit_test.cpp
	g++ -Wall -g -c lab_12_unit_test.cpp
	
item: item.cpp
	g++ -Wall -g -c item.cpp
	
fitem: food_item.cpp
	g++ -Wall -g -c food_item.cpp
	
mitem: magic_item.cpp
	g++ -Wall -g -c magic_item.cpp