lab1test: lab_recursion.o main.o 
	g++ -Wall -g -o lab1 lab_recursion.o main.o 

main: main.cpp
	g++ -Wall -g -c main.cpp

lab_recursion: lab_recursion.cpp
	g++ -Wall -g -c lab_recursion.cpp
	
clean:
	rm *.o lab1